# Generated by Django 4.2.30 on 2026-09-20 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('analysis_type', models.CharField(choices=[('single', 'Single Image'), ('change', 'Change Detection'), ('sar', 'Optical + SAR')], default='single', max_length=20)),
                ('query', models.TextField(blank=True)),
                ('area_of_interest', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SatelliteScene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satellite', models.CharField(choices=[('SENTINEL-1', 'Sentinel-1 SAR'), ('SENTINEL-2', 'Sentinel-2 Optical')], max_length=20)),
                ('scene_id', models.CharField(max_length=255, unique=True)),
                ('acquisition_date', models.DateTimeField()),
                ('cloud_cover', models.FloatField(blank=True, null=True)),
                ('footprint', models.TextField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-acquisition_date'],
            },
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='analysis_images/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.analysisrequest')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_used', models.CharField(choices=[('model_1', 'Model 1 - Classification'), ('model_2', 'Model 2 - Detection'), ('model_3', 'Model 3 - Segmentation'), ('model_4', 'Model 4 - Prediction')], max_length=20)),
                ('confidence', models.FloatField()),
                ('predictions', models.JSONField(default=dict)),
                ('result_geometry', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.analysisrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
